#+STARTUP: showall indent
#+STARTUP: hidestars
#+INFOJS_OPT: view:info toc:t ltoc:nil
#+OPTIONS: H:2 num:nil tags:nil toc:nil timestamps:nil
#+TITLE: Gaming with thin client
#+BEGIN_HTML
(setf
title     "Gaming with a thin client on GNU/Linux at native FPS"
date      "<2013-08-22 Thu>"
meta-keys "Gaming, GNU/Linux, VNC, Thin client"
meta-desc "Gaming with a thin client on GNU/Linux at native FPS speeds"
author    "Matthew Carter")
---
#+END_HTML

* Preface
I wasn't entirely sure it was possible (lots of issues attempting to get
it working over VNC - I made some attempts at TurboVNC/TigerVNC/TightVNC
and VirtualGL, however the easiest way to:

* Get native FPS speeds over your LAN from your thin client to your desktop
was to simply run reverse VNC and launch the game on the native GNU/Linux
desktop display (:0.0).

* Required packages
The following packages are required to make this work:
- x11vnc (on the desktop/host machine)
- vncviewer (on the thin client/laptop - I like the implementation in TigerVNC)
- A game to play
  
* Step one: Installing your packages
Use your package manager to install the necessary packages on the necessary machines.

* Step two: Creating the reverse VNC listener
On the thin client / laptop, being a reverse VNC connection via the following:

#+BEGIN_SRC sh
vncviewer -listen
#+END_SRC

This will cause your VNC application to sit and wait for a connection -
unlike a typical vncserver, the connection will not view your thin client, but will
push it's display outward to you.

* Step three: Connecting to the listener
Assume your thin client is on ip 192.168.0.4
Your fat client/desktop is on ip 192.168.0.5

From your thin client, perform the following commands (note your IP address):

#+BEGIN_SRC sh
ssh 192.168.0.5
#+END_SRC

At this point, you are now ssh'ed into your desktop, run the following:

#+BEGIN_SRC sh
export DISPLAY=":0.0"
x11vnc -connect 192.168.0.4
#+END_SRC

You will now see your thin client pop open a VNC window showing your
native desktop display.

At this point, you can open a terminal in the VNC display and run
whatever game your heart desires.
